import React,{useState,useEffect} from "react";
const Truth=()=>{
   const questions=[
    "Sing the chorus of your favorite song loudly.",
"Go outside and shout 'I love [name of a celebrity]' as loud as you can.",
"Speak in an accent of your choice for the next three rounds.",
"Take a selfie with a random stranger.",
"Post an embarrassing photo of yourself on social media.",
"Eat a spoonful of mustard.",
"Let someone draw on your face with a pen.",
"Wear your clothes backward for the next hour.",
"Do the chicken dance in public.",
"Act like a chicken until it's your turn again.",
"Put an ice cube down your shirt and let it melt.",
"Let someone tickle you for 30 seconds.",
"Speak without closing your mouth for the next two rounds.",
"Try to lick your elbow for a minute.",
"Wear socks on your hands for the next round.",
"Send a text to your crush confessing your love.",
"Go outside and howl like a wolf.",
"Let someone give you a makeover with blindfolded eyes.",
"Draw a funny face on your stomach with a marker.",
"Make up a rap about the person to your left.",
"Pretend to be a waiter/waitress and take snack orders from everyone in the group.",
"Sing everything you say for the next 10 minutes.",
"Let someone write a word on your forehead in permanent marker.",
"Let someone dip your socks in water.",
"Post a Facebook status only using your elbows.",
"Try to juggle three items of the group's choice.",
"Speak in a whisper for the next three rounds.",
"Make up a five-minute dance routine.",
"Wear a funny hat on your head for the next hour.",
"Tell a joke without laughing.",
"Speak with a helium voice for the next three rounds.",
"Recite the alphabet backward in one minute.",
"Wear a sign that says 'Kiss me, I'm single' for the next hour.",
"Take a shot of hot sauce.",
"Walk on your knees until it's your turn again.",
"Eat a spoonful of cinnamon.",
"Let someone draw a mustache on your face.",
"Talk in an Australian accent for the next 10 minutes.",
"Give someone your phone and let them send one text to anyone in your contacts.",
"Let someone tickle you for one minute.",
"Say the alphabet backward in 15 seconds.",
"Wear a funny wig for the next hour.",
"Act like a monkey until it's your turn again.",
"Post a funny video of yourself on TikTok.",
"Give someone in the group a piggyback ride.",
"Say 'banana' after everything you say until it's your turn again.",
"Let someone give you a wedgie.",
"Speak in a baby voice for the next three rounds.",
"Call your crush and sing them a song.",
"Let someone crack an egg on your head.",
"Act like a mime for the next two rounds.",
"Wear a sign that says 'I'm with stupid' and point to the person on your left for the next hour.",
"Speak in slow motion for the next two rounds.",
"Let someone pour a cup of ice down your back.",
"Put a piece of ice in your pants and leave it there until it melts.",
"Act like a cat until it's your turn again.",
"Speak with your mouth full for the next two rounds.",
"Let someone write a word on your forehead with lipstick.",
"Let someone cover your face with shaving cream.",
"Wear a blindfold until it's your turn again.",
"Act like a dog until it's your turn again.",
"Let someone draw on your face with lipstick.",
"Say 'I love you' to a random object in the room.",
"Act like a robot for the next two rounds.",
"Let someone give you a wet willy.",
"Post a photo of yourself making a silly face on Instagram.",
"Give someone a piggyback ride around the room.",
"Say 'I'm a little teapot' after everything you say until it's your turn again.",
"Wear a sock puppet on one hand for the next hour.",
"Let someone put makeup on you blindfolded.",
"Speak in a British accent for the next 10 minutes.",
"Act like a baby until it's your turn again.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Speak in slow motion for the next two rounds.",
"Act like a robot until it's your turn again.",
"Let someone give you a wedgie.",
"Let someone give you a makeover with blindfolded eyes.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Wear a blindfold until it's your turn again.",
"Let someone put tape on your face and rip it off.",
"Let someone draw a unibrow on your face with a marker.",
"Let someone draw on your face with lipstick.",
"Let someone give you a wet willy.",
"Let someone cover your face with shaving cream.",
"Let someone pour a cup of ice down your back.",
"Let someone crack an egg on your head.",
"Let someone draw a mustache on your face.",
"Let someone dip your socks in water.",
"Let someone write a word on your forehead with lipstick.",
"Let someone give you a piggyback ride.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a makeover with their eyes closed.",
"Let someone give you a piggyback ride around the room.",
"Let someone put lipstick on you blindfolded.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put tape on your face and rip it off.",
"Let someone put a blindfold on you and feed you a mystery drink.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone put a blindfold on you and make animal noises until someone guesses what animal you are.",
"Let someone put makeup on you with their eyes closed.",
"Let someone put a blindfold on you and feed you a mystery food.",
"Let someone give you a piggyback ride around the room.",
"Let someone draw a funny face on your stomach with a marker."

   ];
   const [randomQuestion, setRandomQuestion] = useState('');

   useEffect(() => {
    getRandomQuestion();
  }, []); // Empty dependency array to run only once when the component mounts

  const getRandomQuestion = () => {
    if (questions.length === 0) {
      setRandomQuestion("All questions have been asked!");
      return;
    }

    const randomIndex = Math.floor(Math.random() * questions.length);
    const selectedQuestion = questions[randomIndex];
    const updatedQuestions = [...questions];
    updatedQuestions.splice(randomIndex, 1);

    setRandomQuestion(selectedQuestion);
  };

  return (
    <div>
      <p>{randomQuestion}</p>
    </div>
  );
};

export default Truth;